<?php

/**
 * @file
 * This module handles importing product information - either from PIM or BMBWS - and creating nodes.
 * 
 */

/**
 * Implements hook_menu(). 
 */
function bmb_product_import_menu() {

  $items['admin/config/bmb-product-import/settings'] = array(
    'title' => 'BMB Product Import Settings',
    'description' => 'Settings for PIM',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bmb_product_import_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'bmb-product-import.settings-form.inc',
  );
  
  // handles the bmbws import
  $items['bmb-product-import/bmbws'] = array(
    'title' => 'BMBWS Product Update',
    'description' => 'Add and/or Update BMB Product nodes from BMBWS.',
    'page callback' => 'bmb_product_import_bmbws',
    'page arguments' => array(2),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'bmb-product-import.import.inc',
  );
  
  return $items;
}